name: publish nodejs package
description: publish nodejs package
inputs:
    token:
        description: The NPM access token to use when publishing
        required: false
    access:
        description: >
            Determines whether the published package should be publicly visible,
            or restricted to members of your NPM organization.
        required: false
    path:
        description: The path to the package directory.
        required: false
        default: "."
    tag:
        description: The tag to use when publishing the package.
        required: false
        default: "latest"
    dry-run:
        description: Run npm with the --dry-run flag to avoid actually publishing anything.
        required: false
    on_finished:
        description: Run a bash on finished.
        required: false
    on_publish_failed:
        description: Run a bash on publish failed.
        required: false
outputs:
    failed:
        description: "Random number"
        value: ${{ (steps.nodejs.outputs.id == '' || steps.publish_failed.outputs.failed == 'true') && 'true' || '' }}

runs:
    using: "composite"
    steps:
        - uses: actions/setup-node@v5
          with:
              node-version: "24"
        - uses: JS-DevTools/npm-publish@v4
          id: nodejs
          with:
              package: ${{ inputs.path }}/maa-node
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - uses: JS-DevTools/npm-publish@v4
          with:
              package: ${{ inputs.path }}/maa-node-win32-x64
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - uses: JS-DevTools/npm-publish@v4
          with:
              package: ${{ inputs.path }}/maa-node-win32-arm64
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - uses: JS-DevTools/npm-publish@v4
          with:
              package: ${{ inputs.path }}/maa-node-linux-x64
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - uses: JS-DevTools/npm-publish@v4
          with:
              package: ${{ inputs.path }}/maa-node-linux-arm64
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - uses: JS-DevTools/npm-publish@v4
          with:
              package: ${{ inputs.path }}/maa-node-darwin-x64
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - uses: JS-DevTools/npm-publish@v4
          with:
              package: ${{ inputs.path }}/maa-node-darwin-arm64
              tag: ${{ inputs.tag }}
              token: ${{ inputs.token }}
              access: ${{ inputs.access }}
              dry-run: ${{ inputs.dry-run }}
        - name: Finished
          if: always()
          shell: bash
          run: |
              eval $ON_FINISHED || echo "::warning::Failed to eval $ON_FINISHED"
          env:
              ON_FINISHED: ${{ inputs.on_finished }}
        - name: Publish Failed
          id: publish_failed
          if: failure() || steps.nodejs.outputs.id == ''
          shell: bash
          run: |
              eval $ON_PUBLISH_FAILED || echo "::warning::Failed to eval $ON_PUBLISH_FAILED"
              echo "failed=true" >> $GITHUB_OUTPUT
          env:
              ON_PUBLISH_FAILED: ${{ inputs.on_publish_failed }}
