name: publish nodejs package
description: publish nodejs package
inputs:
    token:
        description: The NPM access token to use when publishing
        required: true
    access:
        description: >
            Determines whether the published package should be publicly visible,
            or restricted to members of your NPM organization.
        required: false
    dry-run:
        description: Run npm with the --dry-run flag to avoid actually publishing anything.
        required: false
    on_finished:
        description: Run a bash on finished.
        required: false
    on_publish_failed:
        description: Run a bash on publish failed.
        required: false
outputs:
    failed:
        description: "Random number"
        value: ${{ steps.nodejs.outputs.id == 'undefined' || steps.output_failure.outputs.failed == 'true' }}

runs:
    using: 'composite'
    steps:
      -
        uses: JS-DevTools/npm-publish@v3
        id: nodejs
        with:
            package: assets/MAA-nodejs-package/maa-node
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        uses: JS-DevTools/npm-publish@v3
        with:
            package: assets/MAA-nodejs-package/maa-node-win32-x64
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        uses: JS-DevTools/npm-publish@v3
        with:
            package: assets/MAA-nodejs-package/maa-node-win32-arm64
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        uses: JS-DevTools/npm-publish@v3
        with:
            package: assets/MAA-nodejs-package/maa-node-linux-x64
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        uses: JS-DevTools/npm-publish@v3
        with:
            package: assets/MAA-nodejs-package/maa-node-linux-arm64
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        uses: JS-DevTools/npm-publish@v3
        with:
            package: assets/MAA-nodejs-package/maa-node-darwin-x64
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        uses: JS-DevTools/npm-publish@v3
        with:
            package: assets/MAA-nodejs-package/maa-node-darwin-arm64
            token: ${{ inputs.token }}
            access: ${{ inputs.access }}
            dry-run: ${{ inputs.dry-run }}
      -
        name: Remove NodeJS Release
        if: always()
        shell: bash
        run: |
            eval $ON_FINISHED || echo "::warning::Failed to eval $ON_FINISHED"
        env:
            ON_FINISHED: ${{ inputs.on_finished }}
      -
        name: Output Failure
        id: output_failure
        if: failure() || steps.nodejs.outputs.id == 'undefined'
        shell: bash
        run: |
            eval $ON_PUBLISH_FAILED || echo "::warning::Failed to eval $ON_PUBLISH_FAILED"
            echo "failed=true" >> $GITHUB_OUTPUT
        env:
            ON_PUBLISH_FAILED: ${{ inputs.on_publish_failed }}
