name: publish nodejs package
description: publish nodejs package
inputs:
    access:
        description: >
            Determines whether the published package should be publicly visible,
            or restricted to members of your NPM organization.
        required: false
    on_finished:
        description: Run a bash on finished.
        required: false
    on_publish_failed:
        description: Run a bash on publish failed.
        required: false
outputs:
    failed:
        description: "Random number"
        value: ${{ (steps.nodejs.outputs.id == '' || steps.publish_failed.outputs.failed == 'true') && 'true' || '' }}

runs:
    using: "composite"
    steps:
        - uses: actions/setup-node@v5
          with:
              node-version: "24"

        - name: Publish
          shell: bash
          run: |
              cd assets/MAA-nodejs-package/maa-node
              npm publish --access public
              cd -

              cd assets/MAA-nodejs-package/maa-node-win32-x64
              npm publish --access public
              cd -

              cd assets/MAA-nodejs-package/maa-node-win32-arm64
              npm publish --access public
              cd -

              cd assets/MAA-nodejs-package/maa-node-linux-x64
              npm publish --access public
              cd -

              cd assets/MAA-nodejs-package/maa-node-linux-arm64
              npm publish --access public
              cd -

              cd assets/MAA-nodejs-package/maa-node-darwin-x64
              npm publish --access public
              cd -

              cd assets/MAA-nodejs-package/maa-node-darwin-arm64
              npm publish --access public
              cd -

        - name: Finished
          if: always()
          shell: bash
          run: |
              eval $ON_FINISHED || echo "::warning::Failed to eval $ON_FINISHED"
          env:
              ON_FINISHED: ${{ inputs.on_finished }}
        - name: Publish Failed
          id: publish_failed
          if: failure() || steps.nodejs.outputs.id == ''
          shell: bash
          run: |
              eval $ON_PUBLISH_FAILED || echo "::warning::Failed to eval $ON_PUBLISH_FAILED"
              echo "failed=true" >> $GITHUB_OUTPUT
          env:
              ON_PUBLISH_FAILED: ${{ inputs.on_publish_failed }}
