if (WIN32)
  set(HOST_ARCH "x64-windows")
  set(HOST_EXE_SUFFIX ".exe")
elseif (APPLE)
  set(HOST_ARCH "x64-osx")
else ()
  set(HOST_ARCH "x64-linux")
endif ()

set(PROTO_EXE ${CMAKE_SOURCE_DIR}/MaaDeps/vcpkg/installed/${HOST_ARCH}/tools/protobuf/protoc${HOST_EXE_SUFFIX})
set(PROTO_GRPC_EXE ${CMAKE_SOURCE_DIR}/MaaDeps/vcpkg/installed/${HOST_ARCH}/tools/grpc/grpc_cpp_plugin${HOST_EXE_SUFFIX})
set(PROTO_INDIR ${CMAKE_SOURCE_DIR}/include/Interface/proto)
set(PROTO_OUTDIR ${CMAKE_CURRENT_SOURCE_DIR}/generated)
file(GLOB maa_proto ${PROTO_INDIR}/*.proto)

foreach (src ${maa_proto})
  string(REGEX REPLACE "^${PROTO_INDIR}" ${PROTO_OUTDIR} src_ts ${src})
  if (${src} IS_NEWER_THAN ${src_ts}.timestamp)
    message ("generate ${src}")
    execute_process(COMMAND ${PROTO_EXE} "--proto_path=${PROTO_INDIR}" "--cpp_out=${PROTO_OUTDIR}" ${src})
    execute_process(COMMAND ${PROTO_EXE} "--proto_path=${PROTO_INDIR}" "--grpc_out=${PROTO_OUTDIR}" "--plugin=protoc-gen-grpc=${PROTO_GRPC_EXE}" ${src})
    file (TOUCH ${src_ts}.timestamp)
  endif ()
endforeach ()
